import type { MissionProfile } from './types'

export const MISSION_PROFILES: MissionProfile[] = [
  {
    id: 'retaliation',
    name: 'Retaliation',
    description: 'Defend civilians from ADVENT assault. Enemies arrive in waves across a large map.',
    source: 'base',
    needs: { crowdControl: 3, mobility: 2, aoe: 2, sustain: 1 },
    generalWarnings: [
      'Prioritise mobility — you must reach civilians before ADVENT does.',
      'Bring at least one AoE source to clear clusters efficiently.',
      'Chryssalids may be present — kill them before they reach civilians or your squad.',
    ],
    minSquadSize: 4,
  },
  {
    id: 'guerrilla_op_timed',
    name: 'Timed Guerrilla Op',
    description: 'Objective with a hard turn limit. Speed and burst damage over durability.',
    source: 'base',
    needs: { mobility: 3, burst: 2, actionEconomy: 2, hacking: 1 },
    generalWarnings: [
      'Every soldier must be able to move-and-act in the same turn — avoid Tired/Shaken.',
      'Dashing soldiers (Run and Gun, Implacable, Reflex) can cover the map faster.',
      'Consider skipping enemy pods entirely to hit the objective.',
    ],
    minSquadSize: 3,
  },
  {
    id: 'guerrilla_op_standard',
    name: 'Standard Guerrilla Op',
    description: 'Standard objective mission without a strict turn timer.',
    source: 'base',
    needs: { burst: 2, crowdControl: 2, sustain: 1, hacking: 1 },
    minSquadSize: 3,
  },
  {
    id: 'supply_raid',
    name: 'Supply Raid',
    description: 'Disable alien supply convoy. Hack objectives present; armored vehicles to destroy.',
    source: 'base',
    needs: { hacking: 3, armorShred: 2, burst: 2, mobility: 1 },
    requiredRoles: ['specialist'],
    generalWarnings: [
      'Hack the supply containers for bonus rewards — a Specialist is critical.',
      'MECs and armored targets are common. Bring Shredder or EXO/WAR suits.',
    ],
    minSquadSize: 4,
  },
  {
    id: 'council_vip_extract',
    name: 'Council: Extract VIP',
    description: 'Get a friendly VIP out alive. The VIP is fragile and enemies will rush them.',
    source: 'base',
    needs: { sustain: 3, mobility: 2, crowdControl: 2, burst: 1 },
    generalWarnings: [
      'The VIP cannot fight. Keep enemies suppressed or stunned away from their path.',
      'Bring a Medikit — the VIP can be wounded and needs stabilizing.',
      'Run and Gun or Implacable helps escort the VIP to extract quickly.',
    ],
    minSquadSize: 3,
  },
  {
    id: 'council_vip_capture',
    name: 'Council: Capture Target',
    description: 'Stun a specific enemy and extract them. Heavy return fire expected.',
    source: 'base',
    needs: { crowdControl: 3, burst: 2, sustain: 1, mobility: 1 },
    generalWarnings: [
      'Bring a Stun Lancer or ADVENT-capture item for the takedown.',
      'The capture target often has strong escort — eliminate the escort first.',
      'Psi Stasis on the target preserves them safely while you clear the area.',
    ],
    minSquadSize: 4,
  },
  {
    id: 'facility_assault',
    name: 'Facility Assault',
    description: 'Storm an ADVENT facility to reduce the Avatar Project. Dense corridors, alert enemies.',
    source: 'base',
    needs: { aoe: 3, armorShred: 3, sustain: 2, burst: 2, crowdControl: 1 },
    requiredRoles: ['grenadier'],
    generalWarnings: [
      'Avatar pip reduction is the primary win condition — prioritise this over any other mission this month.',
      'Expect Sectopods and heavily-armored enemies. Bring Shredder + Bluescreen rounds.',
      'Tight corridors punish large pod pulls — advance carefully.',
      'A Specialist with high-tier Gremlin can hack and negate the biggest threats.',
    ],
    minSquadSize: 5,
  },
  {
    id: 'avenger_defense',
    name: 'Avenger Defense',
    description: 'ADVENT attacks the Avenger. Defend it for a fixed number of turns.',
    source: 'base',
    needs: { crowdControl: 3, aoe: 3, sustain: 2, burst: 2 },
    generalWarnings: [
      'Do NOT use your best soldiers — they\'ll be unavailable if wounded. Use your second-best squad.',
      'Defenders need AoE for the waves. Grenadiers are excellent here.',
      'Protect the Avenger objective tile — enemies converge on it.',
      'Lost may appear in WotC Avenger Defenses — prioritise headshots.',
    ],
    minSquadSize: 5,
  },
  {
    id: 'network_tower',
    name: 'Network Tower',
    description: 'Hack an ADVENT communications tower. High-value hack rewards; snipers have excellent sight lines.',
    source: 'base',
    needs: { hacking: 3, burst: 2, mobility: 1, crowdControl: 1 },
    requiredRoles: ['specialist'],
    generalWarnings: [
      'A Specialist is mandatory — the tower cannot be hacked without one.',
      'Elevated position at the tower grants good sight lines. Bring a Sharpshooter.',
      'Reinforcements will drop in after the hack. Have overwatch set before triggering.',
    ],
    minSquadSize: 3,
  },
  {
    id: 'chosen_stronghold',
    name: 'Chosen Stronghold',
    description: '(WotC) Assault and permanently eliminate a Chosen. Waves of Chosen soldiers plus the Chosen boss.',
    source: 'wotc',
    needs: { burst: 3, actionEconomy: 3, crowdControl: 2, sustain: 2, psionics: 1 },
    generalWarnings: [
      'The Chosen has boosted health — bring full beam/plasma tier weapons.',
      'Check the Chosen\'s WEAKNESSES in the Intel tab and bring counters.',
      'Chosen Warlock → bring Psi Operative with Solace for psi immunity.',
      'Chosen Assassin → do NOT bring a melee-heavy squad; she counters melee.',
      'Faction heroes have unique advantages in their Chosen\'s Stronghold.',
    ],
    minSquadSize: 5,
  },
  {
    id: 'alien_ruler_encounter',
    name: 'Alien Ruler Encounter',
    description: '(Alien Hunters) A Ruler reacts after every XCOM action. Requires special tactics to suppress its reactions.',
    source: 'alien_hunters',
    needs: { burst: 3, actionEconomy: 3, crowdControl: 2, sustain: 2 },
    hardCounters: ['psi_stasis', 'spec_haywire', 'spec_tyrant'],
    generalWarnings: [
      'Ruler Reactions: the Ruler acts after EVERY XCOM action — not just turns.',
      'Psi Stasis cancels its reactions for 1 turn — this is the best counter.',
      'Bring Hunter\'s Axe or Alien Ruler items to stun it and pause reactions.',
      'Spread your squad — the Viper King\'s Freeze Breath and Berserker Queen\'s Shockwave are AoE.',
      'DO NOT bring wounded or Tired soldiers — they will die.',
      'Each Ruler gets tougher each time you damage but don\'t kill it. Consider committing fully.',
    ],
    minSquadSize: 5,
  },
  {
    id: 'lost_abandoned',
    name: 'Lost & Abandoned',
    description: '(WotC) Opening mission — XCOM and Reapers vs the Lost with no ADVENT interference. Headshot chains win.',
    source: 'wotc',
    needs: { ammoEfficiency: 3, burst: 2, melee: 2, mobility: 2 },
    generalWarnings: [
      'The Lost grant a FREE ACTION on any one-hit kill. Chain headshots to clear waves without using turns.',
      'Grenades WASTE headshot opportunities — avoid AoE this mission.',
      'Pistols and precise weapons are excellent for headshots on low-HP Lost.',
      'Reapers\' Banish ability is perfect — each hit either kills (free action) or weakens for a follow-up.',
    ],
    minSquadSize: 3,
  },
  {
    id: 'lost_mission',
    name: 'Lost Encounter Mission',
    description: '(WotC) Standard mission complicated by the presence of the Lost. ADVENT and Lost will fight each other.',
    source: 'wotc',
    needs: { ammoEfficiency: 2, crowdControl: 2, burst: 2, mobility: 1 },
    generalWarnings: [
      'Use the Lost and ADVENT against each other — let them fight before intervening.',
      'Headshots on the Lost grant free actions. Plan turns to chain them.',
      'Never grenade a Lost cluster unless you need cover destroyed — you\'re giving up free action chains.',
    ],
    minSquadSize: 4,
  },
  {
    id: 'blacksite',
    name: 'Blacksite',
    description: 'First story mission — retrieve the vial from a heavily defended facility.',
    source: 'base',
    needs: { burst: 3, armorShred: 2, sustain: 2, crowdControl: 2, hacking: 1 },
    generalWarnings: [
      'ADVENT Stun Lancers, Vipers, and Sectoids in force. Bring crowdControl for Sectoid psionics.',
      'The Viper can bind your best soldier — have a plan to rescue them.',
      'No timer — go slow, use concealment to pick your fights.',
    ],
    minSquadSize: 5,
  },
  {
    id: 'forge',
    name: 'Forge',
    description: 'Second story mission — recover the Forge item from a ADVENT genetics lab.',
    source: 'base',
    needs: { hacking: 3, burst: 2, armorShred: 2, crowdControl: 1 },
    requiredRoles: ['specialist'],
    generalWarnings: [
      'Requires the Skulljack or hacking to progress — Specialist mandatory.',
      'Codices will be present: kill in one activation or they clone. Bring high-aim soldiers.',
      'Andromedons — kill the biological pilot after destroying the suit or it explodes.',
    ],
    minSquadSize: 5,
  },
  {
    id: 'psi_gate',
    name: 'Psi Gate',
    description: 'Third story mission — shut down the alien psi network.',
    source: 'base',
    needs: { psionics: 3, crowdControl: 3, burst: 2, sustain: 2 },
    generalWarnings: [
      'You will face Gatekeepers and Avatars. Bring psionics to counter them.',
      'Psi Operative with Stasis can neutralise Gatekeepers while you focus them.',
      'Bring Psi protection (Fortress, Solace) — multiple enemies will attempt mind control.',
    ],
    minSquadSize: 5,
  },
  {
    id: 'final_mission',
    name: 'Final Mission',
    description: 'The Psi Gate final assault on the Avatar facility. Your best six against the Elders.',
    source: 'base',
    needs: { psionics: 3, burst: 3, crowdControl: 3, sustain: 3, actionEconomy: 2 },
    generalWarnings: [
      'Bring your 6 best soldiers in peak condition. No second chances.',
      'Psi Operative is mandatory — Domination on Avatars changes the fight completely.',
      'Full beam/plasma weapons required — everything is heavily armored.',
      'Sustain abilities (Fortress, Sustain psi, field medic) are life insurance.',
      'Bond abilities (WotC) at their most impactful here.',
    ],
    minSquadSize: 6,
  },
]

export function getProfile(id: string): MissionProfile | undefined {
  return MISSION_PROFILES.find(p => p.id === id)
}
